
classdef Fun1 < handle

  properties (SetAccess = private, Hidden = true)
  end

  methods
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function self = Fun1()
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function delete( ~ )
      %% Destroy the C++ class instance
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = F( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %F
      %    OUT1 = F(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 16:03:20
      
      t2 = x.*3.0;
      out1 = [x+exp(t2-y.*3.0)+sin(t2+y.*5.0)-1.0;cos(x-y).^2+x.^2.*(5.3e+1./2.7e+1)+y.^2.*2.0-1.0];
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = J( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %J
      %    OUT1 = J(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 16:03:20
      
      t2 = x.*3.0;
      t3 = y.*3.0;
      t4 = y.*5.0;
      t5 = -y;
      t6 = -t3;
      t7 = t5+x;
      t8 = t2+t4;
      t9 = cos(t7);
      t10 = sin(t7);
      t11 = t2+t6;
      t12 = cos(t8);
      t13 = exp(t11);
      t15 = t9.*t10.*2.0;
      t14 = t13.*3.0;
      out1 = reshape([t12.*3.0+t14+1.0,-t15+x.*(1.06e+2./2.7e+1),t12.*5.0-t14,t15+y.*4.0],[2,2]);
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function [out1,out2] = FJ( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %FJ
      %    [OUT1,OUT2] = FJ(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 16:03:20
      
      t2 = x.*3.0;
      t3 = y.*3.0;
      t4 = y.*5.0;
      t5 = -y;
      t6 = -t3;
      t7 = t5+x;
      t8 = t2+t4;
      t9 = cos(t7);
      t10 = sin(t7);
      t11 = t2+t6;
      t12 = cos(t8);
      t13 = exp(t11);
      out1 = [t13+x+sin(t8)-1.0;t9.^2+x.^2.*(5.3e+1./2.7e+1)+y.^2.*2.0-1.0];
      if nargout > 1
          t15 = t9.*t10.*2.0;
          t14 = t13.*3.0;
          out2 = reshape([t12.*3.0+t14+1.0,-t15+x.*(1.06e+2./2.7e+1),t12.*5.0-t14,t15+y.*4.0],[2,2]);
      end
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = fun( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %FUN
      %    OUT1 = FUN(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 16:03:20
      
      t2 = x.*3.0;
      out1 = (x+exp(t2-y.*3.0)+sin(t2+y.*5.0)-1.0).^2+(cos(x-y).^2+x.^2.*(5.3e+1./2.7e+1)+y.^2.*2.0-1.0).^2;
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = grad( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %GRAD
      %    OUT1 = GRAD(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 16:03:20
      
      t2 = x.*3.0;
      t3 = x.^2;
      t4 = y.*3.0;
      t5 = y.*5.0;
      t6 = y.^2;
      t7 = -y;
      t8 = -t4;
      t9 = t6.*2.0;
      t10 = t7+x;
      t11 = t2+t5;
      t17 = t3.*(5.3e+1./2.7e+1);
      t12 = cos(t10);
      t13 = sin(t10);
      t14 = t2+t8;
      t15 = cos(t11);
      t16 = sin(t11);
      t18 = t12.^2;
      t19 = exp(t14);
      t21 = t12.*t13.*2.0;
      t20 = t19.*3.0;
      t22 = t16+t19+x-1.0;
      t23 = t9+t17+t18-1.0;
      out1 = [t22.*(t15.*3.0+t20+1.0).*2.0-t23.*(t21-x.*(1.06e+2./2.7e+1)).*2.0,t23.*(t21+y.*4.0).*2.0+t22.*(t15.*5.0-t20).*2.0];
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = hess( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %HESS
      %    OUT1 = HESS(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 16:03:20
      
      t2 = x.*3.0;
      t3 = x.^2;
      t4 = y.*3.0;
      t5 = y.*4.0;
      t6 = y.*5.0;
      t7 = y.^2;
      t8 = -y;
      t18 = x.*(1.06e+2./2.7e+1);
      t9 = -t4;
      t10 = t7.*2.0;
      t11 = t8+x;
      t12 = t2+t6;
      t19 = t3.*(5.3e+1./2.7e+1);
      t13 = cos(t11);
      t14 = sin(t11);
      t15 = t2+t9;
      t16 = cos(t12);
      t17 = sin(t12);
      t20 = t13.^2;
      t21 = exp(t15);
      t22 = t14.^2;
      t23 = t16.*3.0;
      t24 = t16.*5.0;
      t27 = t17.*1.5e+1;
      t33 = t13.*t14.*2.0;
      t25 = t20.*2.0;
      t26 = t21.*3.0;
      t28 = t22.*2.0;
      t31 = t21.*9.0;
      t34 = -t33;
      t35 = t5+t33;
      t36 = t17+t21+x-1.0;
      t41 = t10+t19+t20-1.0;
      t29 = -t25;
      t30 = -t26;
      t32 = -t28;
      t37 = t23+t26+1.0;
      t40 = t27+t31;
      t42 = t18+t34;
      t38 = t24+t30;
      t39 = t25+t32;
      t43 = t36.*t40.*2.0;
      t46 = t35.*t42.*2.0;
      t44 = -t43;
      t45 = t37.*t38.*2.0;
      t47 = t39.*t41.*2.0;
      t48 = t44+t45+t46+t47;
      out1 = reshape([t41.*(t28+t29+1.06e+2./2.7e+1).*2.0+t37.^2.*2.0+t42.^2.*2.0-t36.*(t17.*9.0-t31).*2.0,t48,t48,t41.*(t28+t29+4.0).*2.0+t35.^2.*2.0+t38.^2.*2.0-t36.*(t17.*2.5e+1-t31).*2.0],[2,2]);
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function [out1,out2,out3] = fgH( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %fgH
      %    [OUT1,OUT2,OUT3] = fgH(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 16:03:21
      
      t2 = x.*3.0;
      t3 = x.^2;
      t4 = y.*3.0;
      t5 = y.*4.0;
      t6 = y.*5.0;
      t7 = y.^2;
      t8 = -y;
      t18 = x.*(1.06e+2./2.7e+1);
      t9 = -t4;
      t10 = t7.*2.0;
      t11 = t8+x;
      t12 = t2+t6;
      t19 = t3.*(5.3e+1./2.7e+1);
      t13 = cos(t11);
      t14 = sin(t11);
      t15 = t2+t9;
      t16 = cos(t12);
      t17 = sin(t12);
      t20 = t13.^2;
      t21 = exp(t15);
      t22 = t14.^2;
      t23 = t16.*3.0;
      t24 = t16.*5.0;
      t27 = t17.*1.5e+1;
      t33 = t13.*t14.*2.0;
      t25 = t20.*2.0;
      t26 = t21.*3.0;
      t28 = t22.*2.0;
      t31 = t21.*9.0;
      t34 = -t33;
      t35 = t5+t33;
      t36 = t17+t21+x-1.0;
      t41 = t10+t19+t20-1.0;
      out1 = t36.^2+t41.^2;
      if nargout > 1
          t29 = -t25;
          t30 = -t26;
          t32 = -t28;
          t37 = t23+t26+1.0;
          t40 = t27+t31;
          t42 = t18+t34;
          t38 = t24+t30;
          out2 = [t36.*t37.*2.0+t41.*t42.*2.0,t36.*t38.*2.0+t35.*t41.*2.0];
      end
      if nargout > 2
          t39 = t25+t32;
          t43 = t36.*t40.*2.0;
          t46 = t35.*t42.*2.0;
          t44 = -t43;
          t45 = t37.*t38.*2.0;
          t47 = t39.*t41.*2.0;
          t48 = t44+t45+t46+t47;
          out3 = reshape([t41.*(t28+t29+1.06e+2./2.7e+1).*2.0+t37.^2.*2.0+t42.^2.*2.0-t36.*(t17.*9.0-t31).*2.0,t48,t48,t41.*(t28+t29+4.0).*2.0+t35.^2.*2.0+t38.^2.*2.0-t36.*(t17.*2.5e+1-t31).*2.0],[2,2]);
      end
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
  end
end
