
classdef SingularC < handle

  properties (SetAccess = private, Hidden = true)
  end

  methods
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function self = SingularC()
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function delete( ~ )
      %% Destroy the C++ class instance
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = F( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %F
      %    OUT1 = F(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:30
      
      t2 = -y;
      out1 = [t2+exp(x)-1.0;t2+x];
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = J( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %J
      %    OUT1 = J(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:30
      
      out1 = reshape([exp(x),1.0,-1.0,-1.0],[2,2]);
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function [out1,out2] = FJ( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %FJ
      %    [OUT1,OUT2] = FJ(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:30
      
      t2 = exp(x);
      t3 = -y;
      out1 = [t2+t3-1.0;t3+x];
      if nargout > 1
          out2 = reshape([t2,1.0,-1.0,-1.0],[2,2]);
      end
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = fun( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %FUN
      %    OUT1 = FUN(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:30
      
      out1 = (x-y).^2+(y-exp(x)+1.0).^2;
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = grad( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %GRAD
      %    OUT1 = GRAD(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:31
      
      t2 = exp(x);
      t3 = x.*2.0;
      out1 = [t3-y.*2.0-t2.*(-t2+y+1.0).*2.0,t2.*-2.0-t3+y.*4.0+2.0];
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = hess( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %HESS
      %    OUT1 = HESS(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:31
      
      t2 = exp(x);
      t3 = t2.*2.0;
      t4 = -t3;
      t5 = t4-2.0;
      out1 = reshape([t2.*t3-t2.*(-t2+y+1.0).*2.0+2.0,t5,t5,4.0],[2,2]);
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function [out1,out2,out3] = fgH( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %fgH
      %    [OUT1,OUT2,OUT3] = fgH(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:31
      
      t2 = exp(x);
      t3 = x.*2.0;
      t4 = t2.*2.0;
      t5 = -t2;
      t6 = -t4;
      t7 = t5+y+1.0;
      out1 = (x-y).^2+t7.^2;
      if nargout > 1
          t8 = t6-2.0;
          t9 = t4.*t7;
          t10 = t2.*t7.*-2.0;
          out2 = [t3+t10-y.*2.0,-t3+t6+y.*4.0+2.0];
      end
      if nargout > 2
          out3 = reshape([t10+t2.*t4+2.0,t8,t8,4.0],[2,2]);
      end
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
  end
end
