
classdef SingularD < handle

  properties (SetAccess = private, Hidden = true)
  end

  methods
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function self = SingularD()
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function delete( ~ )
      %% Destroy the C++ class instance
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = F( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %F
      %    OUT1 = F(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:31
      
      out1 = [(x.*6.0-y).^4;y+cos(x)-1.0];
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = J( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %J
      %    OUT1 = J(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:31
      
      t2 = x.*6.0;
      t3 = -y;
      t4 = t2+t3;
      t5 = t4.^3;
      out1 = reshape([t5.*2.4e+1,-sin(x),t5.*-4.0,1.0],[2,2]);
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function [out1,out2] = FJ( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %FJ
      %    [OUT1,OUT2] = FJ(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:31
      
      t2 = x.*6.0;
      t3 = -y;
      t4 = t2+t3;
      out1 = [t4.^4;y+cos(x)-1.0];
      if nargout > 1
          t5 = t4.^3;
          out2 = reshape([t5.*2.4e+1,-sin(x),t5.*-4.0,1.0],[2,2]);
      end
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = fun( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %FUN
      %    OUT1 = FUN(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:32
      
      out1 = (y+cos(x)-1.0).^2+(x.*6.0-y).^8;
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = grad( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %GRAD
      %    OUT1 = GRAD(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:32
      
      t2 = cos(x);
      t3 = x.*6.0;
      t4 = -y;
      t5 = t3+t4;
      t6 = t5.^7;
      out1 = [t6.*4.8e+1-sin(x).*(t2+y-1.0).*2.0,t2.*2.0-t6.*8.0+y.*2.0-2.0];
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = hess( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %HESS
      %    OUT1 = HESS(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:32
      
      t2 = cos(x);
      t3 = sin(x);
      t4 = x.*6.0;
      t6 = -y;
      t5 = t3.*2.0;
      t8 = t4+t6;
      t7 = -t5;
      t9 = t8.^6;
      t10 = t9.*3.36e+2;
      t11 = -t10;
      t12 = t7+t11;
      out1 = reshape([t9.*2.016e+3-t2.*(t2+y-1.0).*2.0+t3.*t5,t12,t12,t9.*5.6e+1+2.0],[2,2]);
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function [out1,out2,out3] = fgH( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %fgH
      %    [OUT1,OUT2,OUT3] = fgH(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:32
      
      t2 = cos(x);
      t3 = sin(x);
      t4 = x.*6.0;
      t6 = -y;
      t5 = t3.*2.0;
      t8 = t2+y-1.0;
      t9 = t4+t6;
      out1 = t8.^2+t9.^8;
      if nargout > 1
          t7 = -t5;
          t10 = t9.^6;
          t11 = t9.^7;
          out2 = [t11.*4.8e+1-t3.*t8.*2.0,t8.*2.0-t11.*8.0];
      end
      if nargout > 2
          t12 = t10.*3.36e+2;
          t13 = -t12;
          t14 = t7+t13;
          out3 = reshape([t10.*2.016e+3+t3.*t5-t2.*t8.*2.0,t14,t14,t10.*5.6e+1+2.0],[2,2]);
      end
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
  end
end
