%
% Modified Newton’s method for systems of nonlinear equations withsingular Jacobian
% José L. Hueso, Eulalia Martínez, Juan R. Torregrosa
% Journal of Computational and Applied Mathematics 224
% (2009) 77–83
% http://dx.doi.org/10.1016/j.cam.2008.04.013
%
classdef SingularA < handle

  properties (SetAccess = private, Hidden = true)
  end

  methods
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function self = SingularA()
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function delete( ~ )
      %% Destroy the C++ class instance
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = F( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %F
      %    OUT1 = F(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:29
      
      out1 = [(x-y).*(x-1.0).^2;cos((x.*2.0)./y).*(y-2.0).^5];
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = J( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %J
      %    OUT1 = J(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:29
      
      t2 = x-1.0;
      t3 = y-2.0;
      t4 = 1.0./y;
      t5 = t2.^2;
      t6 = t3.^5;
      t7 = t4.*x.*2.0;
      t8 = sin(t7);
      out1 = reshape([t5+t2.*(x-y).*2.0,t4.*t6.*t8.*-2.0,-t5,t3.^4.*cos(t7).*5.0+t4.*t6.*t7.*t8],[2,2]);
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function [out1,out2] = FJ( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %FJ
      %    [OUT1,OUT2] = FJ(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:29
      
      t2 = x-1.0;
      t3 = -y;
      t4 = y-2.0;
      t5 = 1.0./y;
      t6 = t2.^2;
      t7 = t4.^5;
      t8 = t3+x;
      t9 = t5.*x.*2.0;
      t10 = cos(t9);
      out1 = [t6.*t8;t7.*t10];
      if nargout > 1
          t11 = sin(t9);
          out2 = reshape([t6+t2.*t8.*2.0,t5.*t7.*t11.*-2.0,-t6,t4.^4.*t10.*5.0+t5.*t7.*t9.*t11],[2,2]);
      end
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = fun( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %FUN
      %    OUT1 = FUN(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:29
      
      out1 = cos((x.*2.0)./y).^2.*(y-2.0).^10+(x-y).^2.*(x-1.0).^4;
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = grad( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %GRAD
      %    OUT1 = GRAD(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:29
      
      t2 = x.*2.0;
      t3 = y.*2.0;
      t4 = x-1.0;
      t6 = y-2.0;
      t7 = 1.0./y;
      t5 = -t3;
      t8 = t4.^4;
      t9 = t6.^10;
      t10 = t2.*t7;
      t11 = t2+t5;
      t12 = cos(t10);
      t13 = sin(t10);
      t14 = t8.*t11;
      out1 = [t14+t4.^3.*(x-y).^2.*4.0-t7.*t9.*t12.*t13.*4.0,-t14+t6.^9.*t12.^2.*1.0e+1+t7.^2.*t9.*t12.*t13.*x.*4.0];
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out1 = hess( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %HESS
      %    OUT1 = HESS(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:29
      
      t2 = x.*2.0;
      t3 = x.^2;
      t4 = y.*2.0;
      t5 = x-1.0;
      t7 = y-2.0;
      t8 = 1.0./y;
      t6 = -t4;
      t9 = t8.^2;
      t10 = t8.^3;
      t12 = t5.^3;
      t13 = t5.^4;
      t14 = t7.^9;
      t15 = t7.^10;
      t16 = t2.*t8;
      t11 = t9.^2;
      t17 = t2+t6;
      t18 = cos(t16);
      t19 = sin(t16);
      t20 = t13.*2.0;
      t21 = -t20;
      t22 = t18.^2;
      t23 = t19.^2;
      t24 = t12.*t17.*4.0;
      t29 = t9.*t15.*t18.*t19.*4.0;
      t30 = t8.*t14.*t18.*t19.*4.0e+1;
      t25 = -t24;
      t26 = t10.*t15.*t22.*x.*8.0;
      t27 = t10.*t15.*t23.*x.*8.0;
      t31 = -t30;
      t28 = -t27;
      t32 = t21+t25+t26+t28+t29+t31;
      out1 = reshape([t20+t5.^2.*(x-y).^2.*1.2e+1+t12.*t17.*8.0-t9.*t15.*t22.*8.0+t9.*t15.*t23.*8.0,t32,t32,t20+t7.^8.*t22.*9.0e+1-t3.*t11.*t15.*t22.*8.0+t3.*t11.*t15.*t23.*8.0+t9.*t14.*t18.*t19.*x.*8.0e+1-t10.*t15.*t18.*t19.*x.*8.0],[2,2]);
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function [out1,out2,out3] = fgH( self, varargin )
      % extract arguments
      x = varargin{1};
      y = varargin{2};
      % -----------------

      %fgH
      %    [OUT1,OUT2,OUT3] = fgH(X,Y)
      
      %    This function was generated by the Symbolic Math Toolbox version 9.0.
      %    09-Oct-2021 21:23:30
      
      t2 = x.*2.0;
      t3 = x.^2;
      t4 = y.*2.0;
      t5 = x-1.0;
      t6 = -y;
      t8 = y-2.0;
      t9 = 1.0./y;
      t7 = -t4;
      t10 = t9.^2;
      t11 = t9.^3;
      t13 = t5.^3;
      t14 = t5.^4;
      t15 = t6+x;
      t16 = t8.^9;
      t17 = t8.^10;
      t18 = t2.*t9;
      t12 = t10.^2;
      t19 = t2+t7;
      t20 = t15.^2;
      t21 = cos(t18);
      t22 = sin(t18);
      t23 = t14.*2.0;
      t24 = -t23;
      t25 = t21.^2;
      out1 = t14.*t20+t17.*t25;
      if nargout > 1
          t26 = t22.^2;
          t27 = t14.*t19;
          t28 = t13.*t19.*4.0;
          t33 = t10.*t17.*t21.*t22.*4.0;
          out2 = [t27+t13.*t20.*4.0-t9.*t17.*t21.*t22.*4.0,-t27+t16.*t25.*1.0e+1+t33.*x];
      end
      if nargout > 2
          t34 = t9.*t16.*t21.*t22.*4.0e+1;
          t29 = -t28;
          t30 = t11.*t17.*t25.*x.*8.0;
          t31 = t11.*t17.*t26.*x.*8.0;
          t35 = -t34;
          t32 = -t31;
          t36 = t24+t29+t30+t32+t33+t35;
          out3 = reshape([t23+t13.*t19.*8.0+t5.^2.*t20.*1.2e+1-t10.*t17.*t25.*8.0+t10.*t17.*t26.*8.0,t36,t36,t23+t8.^8.*t25.*9.0e+1-t3.*t12.*t17.*t25.*8.0+t3.*t12.*t17.*t26.*8.0+t10.*t16.*t21.*t22.*x.*8.0e+1-t11.*t17.*t21.*t22.*x.*8.0],[2,2]);
      end
    end
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
  end
end
